### PR TITLE
fix(storage): Updates scalers to do a single data lookup per event

### LINKED ISSUE #203: State lookups use a ton of bandwidth
When running wadm in production at cosmonic, we discovered that wadm uses a ton of bandwidth querying data from the store. Back of napkin math put us around 500GB/month just for querying linkdefs and wadm state data. I will document a more elegant solution in another issue, but we should probably just do a single "snapshot" lookup of state (wadm_state + linkdefs + claims) that is then used by all scalers handling a given event. This means that rather than each scaler querying individually, it will just be queried once.

### PR DESCRIPTION
**Pull request by thomastaylor312**
This works by looking up all the data once per event (whenever scalers are called). This reduces lookups of links by at least 40% and should reduce data usage as well (though not as much as doing some sort of caching would)

Comparing number of `get.links` requests coming over the control topics:

```
❯
rg 'get.links' /tmp/test-e2e-after | wc -l
     272

❯
rg 'get.links' /tmp/test-e2e-before | wc -l
     459
```

Fixes #203

### CODE REVIEW

File: src/storage/snapshot.rs [hunk 1]
```diff
@@ -0,0 +1,161 @@
...
+    fn clone(&self) -> Self {
+        Self {
+            store: self.store.clone(),
+            link_source: self.link_source.clone(),
+            lattice_id: self.lattice_id.clone(),
+            stored_state: self.stored_state.clone(),
+            links: self.links.clone(),
+        }
+    }
+}
```
Comment (brooksmtownsend) [inline src/storage/snapshot.rs:43]: Do you need this to restrict clone to where S, L are clonable?

File: src/storage/snapshot.rs [hunk 2]
```diff
@@ -0,0 +1,161 @@
...
+            link_source,
+            lattice_id,
+            stored_state: Default::default(),
+            links: Arc::new(RwLock::new(Vec::new())),
+        }
+    }
+
+    /// Refreshes the snapshotted data, returning an error if it couldn't update the data
+    pub async fn refresh(&self) -> anyhow::Result<()> {
+        // SAFETY: All of these unwraps are safe because we _just_ deserialized from JSON
```
Comment (brooksmtownsend) [inline src/storage/snapshot.rs:63]: spooky

**Review by brooksmtownsend — APPROVED** [review]
Good stuff 👍🏻

File: src/storage/snapshot.rs (hunk 1 above)
Comment (brooksmtownsend) [reply src/storage/snapshot.rs:43]: To clarify, I think this code is correct just asking if that's the reason why this isn't `derive(Clone)`

Comment (thomastaylor312) [reply src/storage/snapshot.rs:43]: This is for cleanliness here mostly. We know that anything we pass in here will be clone, but many times you can’t actually know that. For us here, if we want to derive clone, we’d have to add a clone bound to the top level strict definition. Then that clone bound bleeds to every other impl of the struct
